stages:
  - build
  - deploy

build-amd64-debian-buster:
  stage: build
  image: debian:buster
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/debian_buster/
    - mv ../*.deb built-packages/amd64/debian_buster/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-debian-bullseye:
  stage: build
  image: debian:bullseye
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/debian_bullseye/
    - mv ../*.deb built-packages/amd64/debian_bullseye/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-armhf-debian-buster:
  stage: build
  image: multiarch/debian-debootstrap:armhf-buster
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/armhf/debian_buster/
    - mv ../*.deb built-packages/armhf/debian_buster/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-armhf-debian-bullseye:
  stage: build
  image: multiarch/debian-debootstrap:armhf-bullseye
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/armhf/debian_bullseye/
    - mv ../*.deb built-packages/armhf/debian_bullseye/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-ubuntu-bionic:
  stage: build
  image: ubuntu:bionic
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/ubuntu_bionic/
    - mv ../*.deb built-packages/amd64/ubuntu_bionic/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-ubuntu-focal:
  stage: build
  image: ubuntu:focal
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/ubuntu_focal/
    - mv ../*.deb built-packages/amd64/ubuntu_focal/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

deploy-package:
  stage: deploy
  image: faucet/dbuilder
  script:
    - cd built-packages/
    - echo "{\"url\":\"https://packagecloud.io\",\"token\":\"$PACKAGECLOUD_TOKEN\"}" > ~/.packagecloud
    - package_cloud push faucetsdn/faucet-test/debian/buster amd64/debian_buster/*.deb || true
    - package_cloud push faucetsdn/faucet-test/debian/bullseye amd64/debian_bullseye/*.deb || true
    - package_cloud push faucetsdn/faucet-test/raspbian/buster armhf/debian_buster/*.deb || true
    - package_cloud push faucetsdn/faucet-test/raspbian/bullseye armhf/debian_bullseye/*.deb || true
    - package_cloud push faucetsdn/faucet-test/ubuntu/bionic amd64/ubuntu_bionic/*.deb || true
    - package_cloud push faucetsdn/faucet-test/ubuntu/focal amd64/ubuntu_focal/*.deb || true
