name: Test building debian packages

on: pull_request

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  debian-package-amd64:
    name: "${{ matrix.distro }} ${{ matrix.release }} ${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: "debian"
            release: "buster"
            arch: "amd64"
          - distro: "debian"
            release: "bullseye"
            arch: "amd64"
          - distro: "ubuntu"
            release: "bionic"
            arch: "amd64"
          - distro: "ubuntu"
            release: "focal"
            arch: "amd64"
          - distro: "ubuntu"
            release: "hirsute"
            arch: "amd64"
          - distro: "ubuntu"
            release: "impish"
            arch: "amd64"
    container:
      image: ${{ matrix.distro }}:${{ matrix.release }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y upgrade
          apt-get -y install devscripts dpkg-dev debhelper equivs
      - name: Bump version
        run: |
          export DEBEMAIL='maintainers@faucet.nz'
          export DEBFULLNAME='Faucet Maintainers'
          debchange -b "Test release"
      - name: Build package
        run: |
          mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
          dpkg-buildpackage -b -us -uc -rfakeroot

  debian-package-other:
    name: "${{ matrix.distro }} ${{ matrix.release }} ${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: "debian"
            release: "buster"
            image: "buster"
            arch: "armv7"
          - distro: "debian"
            release: "buster"
            image: "buster"
            arch: "aarch64"
          - distro: "debian"
            release: "bullseye"
            image: "bullseye"
            arch: "armv7"
          - distro: "debian"
            release: "bullseye"
            image: "bullseye"
            arch: "aarch64"
          - distro: "ubuntu"
            release: "bionic"
            image: "ubuntu18.04"
            arch: "armv7"
          - distro: "ubuntu"
            release: "bionic"
            image: "ubuntu18.04"
            arch: "aarch64"
          - distro: "ubuntu"
            release: "focal"
            image: "ubuntu20.04"
            arch: "armv7"
          - distro: "ubuntu"
            release: "focal"
            image: "ubuntu20.04"
            arch: "aarch64"
          - distro: "raspbian"
            release: "buster"
            image: "buster"
            arch: "armv7"
          - distro: "raspbian"
            release: "buster"
            image: "buster"
            arch: "aarch64"
          - distro: "raspbian"
            release: "bullseye"
            image: "bullseye"
            arch: "armv7"
          - distro: "raspbian"
            release: "bullseye"
            image: "bullseye"
            arch: "aarch64"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.image }}
          shell: /bin/bash
          install: |
            apt-get update
            apt-get -y upgrade
            apt-get -y install devscripts dpkg-dev debhelper equivs
          run: |
            export DEBEMAIL='maintainers@faucet.nz'
            export DEBFULLNAME='Faucet Maintainers'
            mkdir -p /build
            cp -r ${GITHUB_WORKSPACE} /build/package
            cd /build/package
            debchange -b "Test release"
            mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
            dpkg-buildpackage -b -us -uc -rfakeroot
